name: Deploy App

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/deployed/WDP/w4y_fe
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull latest code
        run: git pull origin production

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Configure permission on dist
        run: sudo ../fe-dist-permission-script.sh
